// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjekeAEE4WJlIw9cWeeHheBgKGRMIyCj8',
    appId: '1:414189743198:web:5915ac14969e5bad3098cf',
    messagingSenderId: '414189743198',
    projectId: 'kilimomkononi-fdd14',
    authDomain: 'kilimomkononi-fdd14.firebaseapp.com',
    storageBucket: 'kilimomkononi-fdd14.firebasestorage.app',
    measurementId: 'G-7YRTWLK3MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXmB9nFR_Xk5Qjevkr2qqv23v6vOVePEo',
    appId: '1:414189743198:android:975bfafd25815ae03098cf',
    messagingSenderId: '414189743198',
    projectId: 'kilimomkononi-fdd14',
    storageBucket: 'kilimomkononi-fdd14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtBoYDrSxOj12IqGIzQ_20mjuesHUxTo',
    appId: '1:414189743198:ios:df53110ea93defc03098cf',
    messagingSenderId: '414189743198',
    projectId: 'kilimomkononi-fdd14',
    storageBucket: 'kilimomkononi-fdd14.firebasestorage.app',
    iosBundleId: 'com.example.kilimomkononi',
  );
}
